# Makefile for GNU Make.
# $Id: GNUmakefile 1 2004-10-11 18:06:33Z hex $

include ../../Makedefs.faerion.include

DIRS = 01-raconn 02-raconns 03-radnsperf 04-rahost 05-raflood

include ../../Makedefs.faerion
