# Makefile for GNU Make.
# $Id: GNUmakefile 17 2005-04-18 16:30:38Z vhex $

include ../../Makedefs.faerion.include

TARGET  = library.static
PROG    = rascal.a
SRCS    = $(wildcard util/*.cc *.cc resolver/*.cc)
DEFS   += BUILD_RASCAL RASCAL_HELPERS

include ../../Makedefs.faerion
